project_name: gvm
version: 2

builds:
  - main: ./main.go
    goos: 
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - 386
    ldflags:
      - -s -w

release:
  github:
    owner: magicLian        
    name: gvm           
  draft: false
  prerelease: false

archives:
  - id: my-archive
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    formats: ["zip", "tar.gz"] # Plural form, multiple formats. Since: v2.6
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"